### ISSUE TITLE
Warning in AHUFull

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#103]
In Dymola 2016, I get the following warning:

Check of Cities.Supply.AirHandlingUnit.AHUFull:

The following components are used as state machine states because there are transitions from or to them:
deHuHRS_false
deHuHRS_true
huCHRS_false
huCHRS_true
huPreHHRS_false
huPreHHRS_true
onlyCoolingHRS_false
onlyCoolingHRS_true
onlyHeatingHRS_false
onlyHeatingHRS_true
startState
However, they are not defined as blocks as required.

@PMehrfeld, can you take care of it?

**Comment by PMehrfeld** [comment]
I'll try my best asap.

**Comment by PMehrfeld** [comment]
Dymola declares state machines as "model" by itself. You can change e.g. "model DeHuHRS_true" to "block DeHuHRS_true" (analogous for the other state machines). Then you'll get rid of the warning. I'm not sure if "model" is the better definition, despite the warning, as it is declared by Dymola automatically. But you can also try "block".
Let me know if there are any simulation problems due to AHUFull.mo.

**Comment by mlauster** [comment]
@PMehrfeld; I just recognized that the model is not yet in the AixLib. Would you like to migrate the model into AixLib or are there any objections?

**Comment by PMehrfeld** [comment]
No, I'm fine with that.
