### ISSUE TITLE
Division by zero in HeatConvInside

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#1111]
Devision by zero in model AixLib.Utilities.HeatTransfer.HeatConvInside, calculation method according to Bernd Glück (calcMethod ==2), should be avoided.

**Comment by FelixStege** [comment]
There are two possible ways to remove the zero term. One is to use the max() function and the other is to use the function AixLib.Utilities.Math.Functions.regNonZeroPower. The simulation times are about the same, but regNonZeroPower results in a more realistic behavior (see figure).
![image](https://user-images.githubusercontent.com/38731996/117319631-c98bc680-ae8b-11eb-8cf3-c429143c59ff.png)

One problem that remains is the parameter dT_small, whose value influences the curves shown above strongly. If it is chosen quite small (<=0.01), the function output seems to be incorrect. Further checks are required.

**Comment by FelixStege** [comment]
With commit 2285149c8211066a52b4e2d82672a81c846606c4 the above shown solution is updated using the regstep function, to enable continuous differentiability as shown below.
![regstep](https://user-images.githubusercontent.com/38731996/117838382-94f88000-b27a-11eb-8e0b-4d218fba4a4c.PNG)

**Comment by FelixStege** [comment]
A regression test for a validated model fails. We are currently looking for possible causes and solutions.

**Comment by DaJansenGit** [comment]
The regression test fails because the annual heating and cooling as well as the temperature in the zones slightly changes. But due to the changes this seems leggit to me if in the regarding testcases natural convection is taken into account. I think we only need to create new reference resulst. @SvenHinrichs implemented a new way to create the reference result directly with the CI. Therefore we just need to do a commit with the message:
* `Trigger CI - Update reference results` \
Afterwards the new results should be available in the pipeline as artifacts. :)

**Comment by FelixStege** [comment]
Sounds good! @PMehrfeld has also approved the results, so I will commit this and update the reference results.
