### ISSUE TITLE
HeaterCoolerPI heats and cools at the same time

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixLib#1121]
**Describe the bug**
If both heating and cooling is activated, the model outputs heat and cold demands at the same time.

**Expected behavior**
The controller should either output heat or cold demand, never both.

**Screenshots**

**Solution**

Multiple ideas:
1. Just use one controller for both heating and cooling
2. Raise errors if the bug occurs

**Comment by DaJansenGit** [comment]
A workaround is already implemented here #823

**Comment by FWuellhorst** [comment]
Thanks for the quick reply. 
Wasn't #823 already merged into development? If it's going to be merged soon feel free to close this issue.

**Comment by DaJansenGit** [comment]
Yes it's already merged. But it's more like a work around I would say. Because the way it's implemented you can have over- oder undertemperature in zones, e.g. if heating is required in summer oder cooling in winter. So if you have better ideas to solve this problem it would be a good enhancement :)

**Comment by DaJansenGit** [comment]
@FWuellhorst Based on your suggestion I will close this issue. If you want to reopen, feel free.
