### ISSUE TITLE
Library has uses that want to load both MSL 3.2.3 and MSL 4.0.0

### ISSUE THREAD

**Issue by adrpo** [RWTH-EBC/AixLib#1323]
You use Modelica_DeviceDrivers 1.7.0 which uses MSL version 3.2.3:
https://github.com/RWTH-EBC/AixLib/blob/development/AixLib/package.mo#L8
`Modelica_DeviceDrivers(version="1.7.0"),`
and then you also request MSL version 4.0.0 via uses:
`Modelica(version="4.0.0")),`

You should update Modelica_DeviceDrivers to at least version 2.0.0 which uses MSL version 4.0.0.
https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/releases/tag/v2.0.0

Of course some checks might be needed to see if all the models using components from Modelica_DeviceDrivers  would work correctly with the new version. 

I will see if I can make a PR to fix this.

**Comment by adrpo** [comment]
As far as I see Modelica_DeviceDrivers 2.0.0 is backwards compatible:
https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/releases/tag/v2.0.0
Is written;
- Migrated from Modelica Standard Library 3 (MSL 3) to MSL 4 -> Non-backwards compatible release! However, apart from the MSL 4 dependency this release is compatible to previous releases and no update of user libraries is necessary apart from migrating to MSL 4.

**Comment by casella** [comment]
@FWuellhorst, we are testing the AixLib library with OpenModelica to check what is the success rate, we aim at reaching 100% ASAP.

Currently we are tracking the latest development version of AixLib here: https://libraries.openmodelica.org/branches/master/AixLib_latest/AixLib_latest.html. We thought that master/HEAD would be the right choice for that, but we see you also have a development branch, which is the one @adrpo commited its fixes to, so the current test report is mostly broken.

Can you please comment what is the most appropriate branch for us to test the latest developments of your library?

Eventually, we'd like to test both the latest released version (to check possible regressions cause by bugs introduced in OpenModelica) and the latest development version (to check possible regressions caused by bugs introduced in the library). If we use 1.3.0 for the former one, it will fail because of the issue that was only fixed on the development branch. If you are planning a new release anytime soon (that incorporates @adrpo's fix) then we can wait for that. Otherwise, would you be ok at releasing a 1.3.1 patch release with the correct uses annotations?

Thanks!

**Comment by FWuellhorst** [comment]
@casella Thanks for making this effort to get all libraries running in OpenModelica. 
In general, if we can assist your cause by fixing some models in the AixLib, we are always happy to help.

The best branch to check compatibility with OpenModelica would be the development, the default branch of the AixLib and the one with the latest changes. 
Regarding the release, we will do a patch release!

**Comment by FWuellhorst** [comment]
We added a pre-release, this should be sufficient, or?
https://github.com/RWTH-EBC/AixLib/releases/tag/v1.3.1
