### ISSUE TITLE
Adjust version number in development branch

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#138]
As mentioned in #137, the current top-level `package.mo` lists the version as `0.1.0`. This should be changed in the development branch. As the development branch works towards version v0.3.0, I suggest to change it to `0.3.0` already. Do you agree @PRemmen, @mlauster, @AnaConstantin?

**Comment by PRemmen** [comment]
I would propose to not change this in development branch, but once it is changed in #137 merge the current master into the development branch and thus have the same version number in development and master branch (as the development branch bases on the master).

Does this make any sense? :)

**Comment by marcusfuchs** [comment]
My idea was that when you work with AixLib and switch between master and development back and forth, it may be helpful to also see this in a changing version number. In addition, if your own models have a `uses`-statement, you can only specify whether these models use master or development if they have different version numbers.

**Comment by mlauster** [comment]
I go with @PRemmen, lets keep version numbers of master and development similar. Only before merging development into master, we should increase the version number. Why? Conversion scripts are linked to the version number and `uses`-statement, they are executed only once when Dymola finds a mismatch between `uses`-version number and actual version number of the related library. Dymola automatically sets the `uses`-version number to the actual version after executing the conversion script. Thus, swichting forth and back would only work if we change the `uses`-version number each time manually. Otherwise, we cannot continuously update the conversion script. This only works if we define a clear step where the version number changes and a comprehensive conversion script is available.

**Comment by mlauster** [comment]
This has been solved, right? We should close this issue.
