### ISSUE TITLE
Update naming conventions

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/AixLib#1436]
Naming conventions are not very clear, so they should be updated and sorted more clearly:
https://github.com/RWTH-EBC/AixLib/wiki/Variable-Naming

First steps: 
- Check current version of  Buildings naming convention and update column
- Clear the table and only keep the following columns: meaning, aixlib, buildings, SI units (update to modelica 4.0), modelica type

**Comment by arnoldfuetterer** [comment]
Table does not exist in this version at IBPSA or Buildings anymore. Both libraries know use the naming conventions that are described in the Buildings.UsesGuide (https://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_UsersGuide.html#Buildings.UsersGuide.Conventions)

Progress:

- added naming of sensors to namespaces site (https://github.com/RWTH-EBC/AixLib/wiki/Namespaces)
- deleted old columns with naming conventions for BuildingSystems, Annex60 and IDEAS
- updated Modelica Types of SI Units

Comments:

- Some variable names are not specified as exceptions for three character naming conventions but in Buildings.UsersGuide.Conventions
- We have to decide how we will deal with those. For now they will appear in the table. For exampe: A for Area

Work in Progress:
- update of variable names in current table

**Comment by arnoldfuetterer** [comment]
Progress:

- Namespaces page is updated. It only contains deviations and added details to the Buildings.UsersGuide conventions.
- Variable names page is deleted since it became obsolete
- Table is now used to show Existing namings vs Desired namings (exceptions form naming convention) in the AixLib library

Comments:
- table shall be completed in the long term (maybe by a python script)
