### ISSUE TITLE
Revise LOM MultiZone Example results

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/AixLib#168]
In zone[5] we are getting quite irregular results for the air temperature. As a result is not meant to deliver reliable results, I propose that this is for development.

**Comment by mlauster** [comment]
Okay, I fixed the problem. It was quite challenging as the ventilation volume flow rate share per zone was miscalculated. It was 

1. weighted by the air volume of the zone and not by the required volume flow
1. converted from m3/s to 1/h using the air volume of the entire building and not only by the supplied zones area.

We need to decide if it is a bug or if we just fix it in development.
In addition, we should change the example as cooling a (fairly small) ICT room with a central AHU leads to high energy consumption. The AHU needs to be enabled the entire time, otherwise temperatures rise very high in this zone. 
I propose to delete ICT zone.

**Comment by mlauster** [comment]
closed via #170
