### ISSUE TITLE
Replace OutdoorTemp and TempAndRad

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#198]
The components `AixLib.Fluid.Sources.OutdoorTemp` and `AixLib.Fluid.Sources.TempAndRad` can be removed. Their usage can be easily substituted with the A60 weather model.

**Comment by PRemmen** [comment]
I observed only two usages of `AixLib.Fluid.Sources.TempAndRad`

Fluid.Storage:Examples.StorageSolarCollector.mo
Fluid.HeatExchangers.Examples.SolarThermalCollector.mo

as these are very simple examples with weather data for just one day I propose to replace the models with simple combi time tables instead of using annex models

**Comment by marcusfuchs** [comment]
I agree

**Comment by PRemmen** [comment]
The model `AixLib.Fluid.Sources.TempAndRad` introduced an offset of 0.01 on the Radiation and Temperature given from weather data, due to that, the new results will differ insignificant, because the offset is not set to temperature.
