### ISSUE TITLE
Compare HydraulicResistance and FixedResistanceDpM

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#206]
It may be enough to keep one of these two models.

**Comment by pema1** [comment]
# Can we replace it?
Yes, we can. Both models use the flow equation in the form
`m_flow = c * sqrt(dp)`

In case of FixedResistanceDpM:
`c = k = m_flow_nom / sqrt(dp_nom)`

In case of HydraulicResitance:
`c = sqrt( (d * pi^2 * D^4) / (8 * zeta) )`
with `d` as density, `D` as pipe diameter, `zeta` as dimensionless resistance coefficient.

Therefore, both models are interchangeable if we regard density `d` as constant. However, FixedResistanceDpM uses much more sophisiticated initialization methods (homotropy) and the option to either solve for pressure loss or mass flow rate.

If we would want to use FixedResistanceDpM as a replacement we could define:
`m_flow_nom = sqrt(d * pi^2 * D^4)` and
`dp_nom = sqrt(8 * zeta)`

# Should we replace it?
For the layout of hydraulic networks the engineer (normally) uses the latter aproach as zeta-values for each hydraulic resistances in a circuit can simply be added up (1). You will find them tabulated in literature. The resistance due to pressure losses in straight pipes (2) can be calculated in similar form using flow resistance coefficient ("lambda" in German literature):
`dp = lambda * L/D * d/2 * v^2`, with `v` as velocity.
One can simply add both pressure losses (1) and (2) to get the total pressure loss of the cirquit.

I would argue to keep HydraulicResistance as a convenience model to offer a simple way to account for diverse pressure losses we find in hydraulic networks (which we do not always want to simulate in detail).

# There is a Problem in HydraulicResitance
Issue #232 describes a problem with the current formulation of HydraulicResistance. The solution is given there.

**Comment by marcusfuchs** [comment]
@pema1 : You give a good case for keeping both models. I would agree - would be interesting to get other opinions on this.

**Comment by marcusfuchs** [comment]
This is still relevant, but after merging #234 we can close the issue. Both models will be kept.
