### ISSUE TITLE
Wall Modell: Algorithm for HeatConv_inside should be selectable via parameters upper modell level

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#215]
Now the default algorithm is always used

**Comment by TobiasBlacha** [comment]
I changed the wall model so that now the mode for the calculation of the convection at the inner surfaces is selectable via parameters on upper model level. I have created the branch "issue215_WallModel" outgoing from the master, for a pull request the master must first be merged into the development.

**Comment by marcusfuchs** [comment]
@TobiasBlacha 
Are there changes in the master, that are not in development? And was there a specific reason for branching of the master, rather than from development? See [our workflow](https://github.com/RWTH-EBC/AixLib/wiki/Contribute-to-AixLib).

**Comment by TobiasBlacha** [comment]
Yes, the last bugfix in the master is not yet in the development. I have worked inadvertently outgoing from the master and i noticed it later. The development is already merged into this branch.
