### ISSUE TITLE
OpenModelica: Translation ERROR, couldn't find class

### ISSUE THREAD

**Issue by R33B** [RWTH-EBC/AixLib#257]
I added the within lines in the .mo files as described in #RWTH-EBC/TEASER#254

See: [SUH_1.zip](https://github.com/RWTH-EBC/AixLib/files/315856/SUH_1.zip)

Therewith OpenModelica opens without errors the package SUH_1 which is located at: 

> ...\Anaconda2\Lib\site-packages\teaser\OutputData\Project\

Trying to simulate the SUH_1 I get the following errors:

> [1] 11:39:18 Scripting Warning
> Requested package Modelica of version 3.2.1, but this package was already loaded with version 3.2.2. You might experience problems if these versions are incompatible.
> 
> [2] 11:39:25 Syntax Warning
> [.../Anaconda2/Lib/site-packages/teaser/OutputData/Project/SUH_1/SUH_1.mo: 43:9-43:36]: Lexer treating \ as \\, since \I is not a valid Modelica escape sequence.
> 
> [1] 11:40:52 Translation Warning
>**Ignoring unknown experiment annotation option: __Dymola_Algorithm = "Dassl"**
> 
> [2] 11:40:52 Translation Error
> **[SUH_1: 5:7-7:3]: Klasse Project.SUH_1.SUH_1_DataBase.SUH_1_base konnte nicht im Geltungsbereich von SUH_1 (looking for a function or record) gefunden werden.**
> 
> [3] 11:40:52 Translation Error
>**Error occurred while flattening model SUH_1**
>

**Comment by R33B** [comment]
PS: I get the same errors on trying to export the model as FMU.

**Comment by mlauster** [comment]
These errors are related to your aims to get rid of the other errors. You renamed your package and still have some `Project` pathes in your package. In addition, you ended your `within`-statements with a `.`. However, I could get rid of one error only by creating a new package structure in Dymola and copy your files into it. Unfortunately, without your history, I cannot track down this error. I will adapt TEASER to the already known issues and see if these models face the same problem.
Your model is not simulatable as you do not define all boundary conditions. 
[SUH_1_new.zip](https://github.com/RWTH-EBC/AixLib/files/325190/SUH_1_new.zip)
Since this is not related to AixLib or TEASER, I will close this issue without opening one for TEASER.

**Comment by R33B** [comment]
Thank you very much, the declaration of the within-statements is now comprehensible and `SUH_1_new` opens in OM, giving the following error as you mentioned, because input ist missing:

> [21] 11:52:42 Symbolic Error
> Zu wenige Gleichungen - unterbestimmtes System. Das Modell hat 824 Gleichung(en) und 826 Variable(n).

Though, I would have expected, that the FMU export is possible anyway, as I could give the missing information to the FMU-block e.g. in Simulink. But `SUH_1_new` is not exportable to FMU either. 

> [45] 11:53:32 Translation Error
> Interner Fehler SimCode: The model SUH_1_new.SUH_1 could not be translated to FMU

Is this a general problem or a new issue?

**Comment by mlauster** [comment]
I'm not quite sure if this is a problem in any case, I'm not that experienced with FMU export, so I can't judge if it's a problem of your individual model or the AixLib. Could you try to track down the problem and raise an issue if it is AixLib related?

**Comment by R33B** [comment]
Ok, I will try to figure it out during the next days and raise an issue, if necessary.
So far, I can say that the subclass `Multizone `within the `SUH_1_new` is exportable whereas the entire `SUH_1_new` is not.
Could you let me know, whether the FMU export with Dymola does work?

**Comment by mlauster** [comment]
It won't work in Dymola, since the model is incomplete. I think what you would like to have is to have all not connected inputs of the `ThermalZone` model as input at the top-level and then export this as FMU. For this, you need to define the inputs (and outputs) on top-level, e.g. as a connector. And then you need to connect them to the corresponding inputs of the `ThermalZone` model. How should OpenModelica (or Dymola) otherwise know what for connectors you would like to have?
By the way, issues are not for support, so we should end this discussion here.

**Comment by R33B** [comment]
Allright, thank you very much for your feedback and the support.
I will let you know whether your suggestion worked or not.
