### ISSUE TITLE
LimPID with integrator reset

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/AixLib#261]
It should be possible to reset the integrator in `AixLib.Controls.LimPID`.

**Comment by marcusfuchs** [comment]
@PMehrfeld 
I assume you mean the model `AixLib.Controls.Continuous.LimPID`? This model is not originally a model of *AixLib*, but merged from *Annex60*. Therefore, it would be good to close this issue here and create a new one on the [Annex 60 repo](https://github.com/iea-annex60/modelica-annex60). Would be great of we could find a solution to this problem within the A60 community.
