### ISSUE TITLE
Move  Fluid.HeatExchanger.HeatPump

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/AixLib#264]
to new Annex 60 package `Fluid.HeatPumps`. Don't forget BaseClasses and Examples

**Comment by PMehrfeld** [comment]
Currently in branch `Annex60_HP_review` there still exist the models `AixLib.Fluid.HeatPumps.HeatPump_simple` and `AixLib.Fluid.HeatPumps.HeatPump_simple`.
The detailed model provides much more parametrization possibilities like directly using manufacturers' data (provided via records) or a capacity control via a polynomial function and diverse corrections. Whereas the simple HP can only be fed via tabulated data. 

If you parametrize the two models as equivalent as possible we reach similar results, here displayed by the condenser output temperature:
![temp_condenser](https://cloud.githubusercontent.com/assets/11769433/19280130/b8245d78-8fe4-11e6-9347-651ae8ae041a.JPG)

But I vote for keeping both models since a test simulation shows an almost 3 times slower simulation speed for the detailed model:
![cpu_times](https://cloud.githubusercontent.com/assets/11769433/19280176/f658748a-8fe4-11e6-8db5-57303afa1c4d.JPG)

**Comment by marcusfuchs** [comment]
I think the model names should be camel case, but appart from that I see no reason not to keep both models.

**Comment by PMehrfeld** [comment]
@marcusfuchs : changed it.
But 2 more questions @KristianHuchtemann before PR:
1. Can we add more records of manufacturers' data?
2. I have replaced the orifice from the MSL with `AixLib.Fluid.FixedResistances.FixedResistanceDpM`. Is this okay?

**Comment by PMehrfeld** [comment]
Regarding:
1. I will transfer some more records into AixLib
2. The prior used model from MSL `Modelica.Fluid.Fittings.GenericResistances.VolumeFlowRate` leads to stable initialization when it comes to a more complex simultion, whereas when using `AixLib.Fluid.FixedResistances.FixedResistanceDpM` the simulation is not able to initialize.

I tried the whole morning to get the simulation start but couldn't find a working solution.
It would be beneficial if there is someone else who want to have a look at the complex test model. So please ask me, I will send the total model.

Otherwise I would suggest to go with the model of the MSL.

**Comment by PMehrfeld** [comment]
I have transferred all records that are based on public manufacturers' data to AixLib.

The detailed heat pump model should now be fully based on the Annex60 fluid.
Anyway, I have found out that the model `Modelica.Fluid.Fittings.GenericResistances.VolumeFlowRate` in general seems to stabilize fluid simulations. The component still solved the initialization problem in the complex hydraulic network, but it need not necessarily to be part of the heat pump model but of the hydraulic circuit.

See #298 for PR.
