### ISSUE TITLE
ThermalZone example does not work with MSL 3.2.1

### ISSUE THREAD

**Issue by mschumacher247** [RWTH-EBC/AixLib#326]

**Comment by mschumacher247** [comment]
ThermalZone example doesnt check with Dymola 2016 and MSL 3.2.1. Using Dymola 2017 and MSL 3.2.2 did not show this problem. When unloading MSL 3.2.2 and reloading MSL 3.2.1 in Dymola 2017 the error did not occur either. See error message attached

![error_message](https://cloud.githubusercontent.com/assets/8257582/21820009/57e79980-d76e-11e6-8231-288d69403ca3.png)

**Comment by mlauster** [comment]
I think that's a bug of Dymola 2016. They seemed to have changed some internals links for expandable instances that are vectorized. The current version of the models you mention have been developed in Dymola 2017, so I never ran into that problem. Is that something crucial for you, @mschumacher247? Or is it fine working with Dymola 2017? We should the models in latest version of OMEdit to see how this is handled in other enviroments.

**Comment by marcusfuchs** [comment]
@mlauster 
We had a short discussion about this and the idea of this issue was to just write it out here, assign a *wontfix* label and close it. This way we have it documented and hope that if someone runs into the same problem, they can find the solution more quickly, as it may be hard to directly come up with the solution from the text of the error message. If anyone has bandwidth and need to fix this, they of course may reopen the issue, but currently it does not seem necessary.
