### ISSUE TITLE
Asses model for HydraulicResistance to AixLib

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#333]
- [x] Compare to models from Annex60 and see if there is any advantage in transfering such a model

- [x] If no advantage identified write a conversion script for the new model to be used

- [x] If advantage present, transfer the model

**Comment by PMehrfeld** [comment]
- I would not transfer any model of our old HVAC library, since current `AixLib.Fluid.FixedResistances.HydraulicResistance` is easier to use than `HVAC.Components.HydraulicResistance.HydResistance`.
- Also models of package `HVAC.Components.HydraulicResistance.T_elements` are not really necessary as everyone can compose ideal junctions and hydraulic resistances by themselves.
- Further information see #366

**Comment by pema1** [comment]
In `AixLib.Fluid.FixedResistances.HydraulicResistance`
- Should we have a reverse formulation for m_flow = f(dp) also?
- density (rho) should maybe based on the average static pressure in the pipe? Currently only considers port_a.p regardless of flow direction.

**Comment by PMehrfeld** [comment]
Thanks for these hints @pema1!

After evaluating particular models of MSL and IPBSA library, I am modelling a suitable hydraulic resistance with `zeta` and `diameter` as main parameters. I extend `AixLib.Fluid.BaseClasses.PartialResistance` to stay consistent with  Annex 60 / Project 1 conventions.

To react on your two bullet points:

- Now a `from_dp` is considered
- Since I am using the functions `Modelica.Fluid.Utilities.regRoot2` and `...regSquare2` I take a positive or negative direction into account via `rho_a` and `rho_b`.

Further commits will come soon.

**Comment by AnaConstantin** [comment]
Closed via pull request #366
