### ISSUE TITLE
Where is BuildingPhysicsExample?

### ISSUE THREAD

**Issue by tbeu** [RWTH-EBC/AixLib#352]
Some previous version of AixLib (< v0.4.0) contained AixLib.Building.LowOrder.Examples.BuildingPhysicsExample which is missing in master now. Has it been renamed and moved or deleted?

**Comment by tbeu** [comment]
OK, it is gone by aa9d36c63932c033406c646a94745ceb0df1958f. Is there any replacement model?

**Comment by mlauster** [comment]
This is because we switched to new model cores in `AixLib.ThermalZones.ReducedOrder`. `AixLib.ThermalZones.ReducedOrder.Examples.SimpleRoomTwoElements` is quite similar to the old example you mentioned, except infiltration and sunblinds. However, both are also available with the now core models. The new core models are extended and reworked versions and cover all functionalities of the old ones. The old models at `AixLib.Building.LOM` will be deleted with one of the next releases, see https://github.com/RWTH-EBC/AixLib/issues/276. Is there a specific reason you ask for that example?

**Comment by tbeu** [comment]
BuildingPhysicsExample was one of the models which needed to be investigated further for some simulation issue. If this model is gone in master now I will checkout the latest version containing it.

**Comment by mlauster** [comment]
I can close this issue then, @tbeu?
