### ISSUE TITLE
Merge Modelica IBPSA Library into AixLib

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#378]
We should update AixLib to the latest version of the [Modelica IBPSA Library](https://github.com/ibpsa/modelica-ibpsa). For this, `mergeAnnex60toAixLib.py` needs to be replaced and updated as well.

**Comment by marcusfuchs** [comment]
I tried merging the new library to AixLib.  The result is on branch [`issue378_ibpsa2aix`](https://github.com/RWTH-EBC/AixLib/tree/issue378_ibpsa2aix). I'll check the result. Would be great if others (e.g. @mlauster @PRemmen @PMehrfeld @MichaMans @AnaConstantin ...?) could also check whether this went right.

**Comment by PMehrfeld** [comment]
@marcusfuchs: When I do a Check (F8 in Dymola) for `AixLib`, I receive the same errors / warnings / messages as when checking the current `development`.
Thus, at least in the context of a package check, the merge seems to have worked properly.

Btw: 2 errors occur because `DataBase.Pipes.PipeBaseDataDefinition` is missing in the model `AixLib.DataBase.Storage.BufferStorageBaseDataDefinition`.
I do not know whe the package for the pipes in `DataBase` has been deleted.

**Comment by marcusfuchs** [comment]
@PMehrfeld Thanks for checking. As far as I can see, the Database entries for pipes are also missing in our current `development` branch. Therefore this does not seem to be a problem with the IBPSA merge. Therefore I suggest to fix that in a separate issue.

Upon loading the library, I got another error because the package order of `AixLib.Utilities.Sources` wrote `ncDataReader` starting with `n` while the class is named `NcDataReader`. I adjusted the `package.order` to also use `NcDataReader`.

Do we want to go ahead an create a pull request for this, leading to a v0.5.0 release, or does anyone want their open pull requests to be merged before that?

**Comment by mlauster** [comment]
@PMehrfeld, @marcusfuchs, I fear the pipes-stuff was me for #285. I searched for usages, but couldn't find any. I will revert that by re-opening that issue. But I agree, that is not related to this issue here.

**Comment by mlauster** [comment]
Regarding the Release, as a last check it would be helpful what for new files have been added. Sometimes, we still have deleted models as files in our structure as Dymola only changes the package.order but does not physically delete models. When merging with buildingspy, all that files as discovered and re-added to the package.order files. Unfortunately, Firefox is struggling with github and I cannot check what files have been added. If all is fine, I'm fine too and vote for a release.

**Comment by marcusfuchs** [comment]
At least from the changes in the package orders, I cannot see any old models re-appearing.

**Comment by PMehrfeld** [comment]
@marcusfuchs: Thanks for capitalizing the file name and model name in the order file. I saw this too, but forgot to commit it ;)

To avoid "file debris" we could additionally store a copy of AixLib in directory mode in Dymola so that the whole library will be stored in file structure. Then delete library folders that belong to the library. Of course not the folders `Images` and `Resources` and we must keep the files `.copiedFiles.txt` and `License.htm`.
Because some models are still stored in on file, e.g. `AixLib.BoundaryConditions.Types`.
Clearly a **problem** are all the white space changes that would be pushed as well. And that we maybe will receive merge conflicts due to this procedure.

What do you think?

**Comment by marcusfuchs** [comment]
I hope that in the future we may be able to rely on unit testing, continuous integration, and heavy usage of AixLib (fingers crossed...). This would hopefully catch any merging errors. In the meantime, I would be OK with some manual checking efforts. If we see this does not work, we could go back to your suggested work-around?

Also, as there are no objections, I will go ahead and create a merge request for this, bumping us up to v0.5.0.

**Comment by AnaConstantin** [comment]
Shouldn't all models be in separate files anyway, in order to ensure compatibility with OpenModelica?

**Comment by marcusfuchs** [comment]
I agree that this would be much better. We could set the conversion to everything saved in files as part of the v0.6.0 milestone? Or should we do this for v0.5.0? Not sure whether that would affect the numerous open pull requests.

**Comment by AnaConstantin** [comment]
I suggest to open an issue for the v 0.6.0. milestone for this. However, if these models come from the IBPSA library, such as AixLib.BoundaryConditions.Types, does it make sense to do it in AixLib?

**Comment by marcusfuchs** [comment]
In general, I would suggest to always open an issue in AixLib so that everyone has the chance to be aware of the problem. If the problem concerns a model/package from the IBPSA Modelica Library, we can open another issue in the IML repository, referencing our AixLib issue.

**Comment by mlauster** [comment]
closed via #381
