### ISSUE TITLE
Possible restructuring of the Modelica IBPSA Library

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#386]
In ibpsa/modelica-ibpsa#778 @mwetter is proposing a major restructuring of the Modelica IBPSA Library that would also affect AixLib. This issue is to make everyone aware of the discussion to happen in ibpsa/modelica-ibpsa#778 and to discuss the implications for AixLib. 

Currently, the basic structure of our libraries is a more generic one. E.g. fans and pumps are both modeled with `AixLib.Fluid.Movers`, as the physical principle behind both components is the same and the medium can be changed by the user. The advantage of this approach is that there are fewer models. A disadvantage is that from an engineering perspective, users may prefer separate packages for air and water based systems. The proposal for restructuring goes in the direction of that (maybe it's fair to call it that) user-centered approach. 

As this is a major design issue with large implications for all IBPSA-based libraries, it would be great to get everyone's opinion on this regarding the future structure of AixLib. What do you think?

**Comment by mlauster** [comment]
Being more user-centered is always a good idea and with the current structure we had the same confusion (where do I find a fan?) already at our institute. So I really love the idea of having an easy-to-understand structure with maybe again an `HVAC`-package. On the downside, this would mean a lot of work, in particular regarding conversion scripts. And before that transformation, we should integrate all internal EBC-libs models, doing both at the same time is highly complex. The benefits outweigh anyway! That gets my thumbs up!

**Comment by AnaConstantin** [comment]
For me this is awsome news @marcusfuchs. I totally agree that we should have a user-centered approach, because we want other people, as just us the developers, to start using the libraries. I do not think more packages are a problem, as for me "fan" and "pump" together are a lot easier to understand when just reading them, than "movers". As a user I want to understand quickly what kind of models are in package just by reading the name, as opposed to going into that package and start reading the descriptions of the models. 
@mlauster I agree that the conversion scripts are extra work, but just restructuring is quite doable by conversion script. 
I think we can even take an engineering-based approach when naming the packages like energy generation, distribution, storage, delivery or something like that.

**Comment by TobiasBlacha** [comment]
I also think a new structure of the library makes sense. Especially the fluid package is confusing for the user, for example, I would not suspect the AixLib.Fluid.Solar.Electric.PVSystem model in this package. I think it is helpful to separate the models according to the medium. In addition, I think the idea to separate the models by their function is very good. For the user, it is much easier to find a model when the AixLib is structured in an engineering-based approach as suggested by @AnaConstantin.

**Comment by ThomasSchuetz** [comment]
I also support the idea of restructuring AixLib.

The current structure has always been counterintuitive to me. Since I do not use AixLib on a regular basis, I usually need a few minutes to get back into the logic behind the ordering in this library. Restructuring AixLib would probably solve this issue.

**Comment by MichaMans** [comment]
I vote for a more intuitive structure and therefore for the restructuring!

**Comment by mschumacher247** [comment]
Since we had a lot of effort developing these Libraries (and possibly will have in the future) it would be reasonable to be a bit more "customer oriented". Maybe we can activate a broader user basis, apart from academia. Therefore switching to a more user-centric approach would be a good idea.

**Comment by JSchiefelbein** [comment]
Dito: If the restructuring process enables a simpler and more intuitive usage of the IBPSA (and AixLib), it should be performed.

**Comment by marcusfuchs** [comment]
Even though not everyone gave their opinion until now, it seems the general opinion is very much in favor of the restructuring. I will therefore communicate this view to the IBPSA Modelica Libary group. Nevertheless, feel free to add to the discussion, as I would expect that this topic will be with us for a while and it's important to everyone.

**Comment by mlauster** [comment]
I will close this issue for now as the decision has been made. When we start with implementing a new structure in dependence of IBPSA library, we can reopen it.
