### ISSUE TITLE
Discussion and Improvement of Filtered Valve Opening 

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#389]
## What is the problem?

- The filtered valve opening of the valve models in Fluid.Valves is based on a 2nd order filter. As a result, the opening and closing of the valve starts some seconds after changing the input signal (see the picture below). 
To my mind, the valve should change the direction (opening or closing) directly or at least more faster after a change.

## Why do we want to solve it?

- We want to improve the models.

## How do we want to solve it?

- We should discuss the behaviour of a real valve and compare it with the models.

**Comment by alexanderAKU** [comment]
![valvetest](https://cloud.githubusercontent.com/assets/18326590/26112475/48f709ea-3a58-11e7-875d-b42b1f965980.PNG)

The picture shows the filtered valve opening (val.y_actual) for a changing input or set value (val.y).
I think that a delay of around 6s is too long. 
I used the preset parameter values for this example.

@AnaConstantin and @pema1  what do you think about that?

**Comment by AnaConstantin** [comment]
@alexanderAKU I assume you are refering to the models from the MSL. The filtered opening option should be used for stability reasons, as explained in Modelica.Fluid.Valves.BaseClasses.PartialValve. The parameters of the filter should be set according to the desired response of the system where the valve is integrated. Additionally you can go inside the model and change the type of filter use to one that you might find more appropiate.
However if you want the opening and the closing of the valve to have a different profile, I suggest doing this using the valveCharacteristic, or an additional block.
Could you please open an branch for this issue and put the example you used in it, since I'm quite intrigued by the picture you have showed. The response of the valve seems really slow for what I assume are the preset parameters (risetime = 1, leckage = 1e-3)

**Comment by pema1** [comment]
@alexanderAKU I think that the slow acceleration in the beginning is not right and neither the slowdown in the end. I would expect a linear change of position for a normal motor valve. Using the filter for stability, however, I find a good approach - maybe with a smaller time constant.

For valve actuators I find some example values (full stroke time):

* Johnson Controls VA-703x: 3 min and 5 min
* Johnson Controls VA-704x and VA-706x: 3 min (for 3 mm/4.5 mm)
* Johnson Controls VA-7450-x and VA-7452-x: 45 s (for 3 mm/5 mm)
* Johnson Controls VA-7150: 10 s/mm (@ 20 mm -> 200 s)
* Johnson Controls VA-7700: 200 mm @ 50 Hz (167 s @ 60 Hz)
* Johnson Controls VA-7150: 6 s/mm and 3 s/mm
* Belimo LR24AX-MPX (5NM, 24VAC/DC): 90 s
* Sauter AVM 115SF132(500N 24VAC/DC):  60/120s

Normally, valve and motor have a [hysteresis](http://www.gomatlab.de/download,id,7221.html). I would model the valve stem postion with the hystereis and use the valve characteristic as implemented. Björn Flieger implemented a hystersis model in his masters thesis on a thermostatic valve we have in our internal HVAC library at EBC. The solution then was to use a trigger signal at a given interval to determin the current and previous stem position in order to determin a switch in direction. It turned out not to be usable as Dymola solvers could not handle those systems well.

**Comment by mlauster** [comment]
@alexanderAKU, is there still interest in further discussion or should we close this issue?

**Comment by PMehrfeld** [comment]
@alexanderAKU : Is this issue still relevant for you?

**Comment by PMehrfeld** [comment]
@alexanderAKU : I will close this issue. Feel free to reopen it, if work will be continued here.
