### ISSUE TITLE
Add District Heating and Cooling models

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#403]
## Update

We are trying to make a renewed effort to add DHC models to AixLib, concentrating our previous activities from different projects.

This issue will be the central reference for a branch `issue403_dhc`, in which we will continue our development until a first version is ready for merging to the `development` branch. We may require different feature branches that first merge to `issue403_dhc`. We'll use separate issues and PRs to `issue403_dhc` for this. In this issue, we will try to keep an overview of current activities.

Feel free to participate. Currently, @MichaMans @TobiasBlacha  and me are working on this topic.

First steps are:

- [x] Merge new IBPSA pipe model via `development` in #515
- [x] Create reference models for supply line networks
- Continue with closed loop system models

----------------------
<del>

## What is the problem?

- Assembling district heating and cooling network models from components on only one hierarchical level will probably be cumbersome, especially if we want to have different models to represent the networks with different levels of detail. Therefore, I propose to add base classes as containers for supply nodes, demand nodes, and pipe elements. 

## Why do we want to solve it?

- Such containers for the basic building blocks of DHC systems will hopefully provide an easy-to-use interface to model DHC systems in a large variety of setups. 

## How do we want to solve it?

#402 already adds a first reference network for hydraulic validation. Continuing this work, I'll add the base classes, a very simple first implementation of each network component, and an example recreating the reference network using the newly introduced modules. This may also show some need to modify the models added in #402. 

</del>

**Comment by MichaMans** [comment]
As discussed with @marcusfuchs we should consider a IdealHeatSink (or flow sink) with a input connector. With that, we are able to use DemandTables from text or ncDataReaders or .mos scripts, or outputs of other simulation classes, e.g. the thermal zone idealheatercooler
- [ ] Add IdealHeatSinkInput class

**Comment by PMehrfeld** [comment]
Just as a quick hint: We have a easy-to-use converter for *.mat --> *.nc in our ebc_python_library :)

**Comment by PMehrfeld** [comment]
@MichaMans and @TobiasBlacha : It seems that you two are working now on this issue. Any chance to complete it (maybe together with @marcusfuchs) for the next milestone?

**Comment by MichaMans** [comment]
@PMehrfeld I think this is and will be a WIP issue for the next weeks/month, but we can have a look at it and merge it at the current state into development. That would make it a bit more transparent

**Comment by PMehrfeld** [comment]
Thanks for the updates. I set this issue's milestone to a higher version and additionally assigned you, @MichaMans and @TobiasBlacha.

**Comment by MichaMans** [comment]
As the feature branches of this issue are getting a bit confusing I'm going to delete them:

- _supplyIn is already integrated in _dhc via #517 (should be deleted)
- _pump_supply should be integrated more or less in _supplyIn (I'm going to delete it as well)
- _static_pipe is also integrated in _dhc (should be deleted)
- _consthp branch is ahead of _dhc (I'll create a PR for this)

@marcusfuchs @TobiasBlacha any objections?

**Comment by marcusfuchs** [comment]
No objections.

**Comment by MDHering** [comment]
@MichaMans @TobiasBlacha @marcusfuchs Is anyone using the OpenLoop/HeatPumpCarnot model? I have two minor changes, that I want to add and don't want any other models to fail.
Changes are:
- assign dTDesign to temperatureDropHP.k
- Add minimal temperature difference on district heating side (avoids return flow temperature from going out of bounds)

**Comment by MichaMans** [comment]
If someone is currently working with that model, then @TobiasBlacha . From my side, every addition is an enhancement 👍

**Comment by TobiasBlacha** [comment]
@MDHering I'm not working with the model at the moment, but I think the two proposed changes are good.

**Comment by MichaMans** [comment]
@MDHering @TobiasBlacha 
I did some small revisions of the partial supply model, set the time constant (tau) for temperature sensor to zero (reason: simulations with euler solver and fixed time step of 1s were otherwise not feasible), flipped the sensor for aesthetic reasons, implemented a Q_flow for the calculation of the heating power in the supply station.

**Comment by MDHering** [comment]
@MichaMans @TobiasBlacha  I tried to find a way to set additional pressure losses of the plugFlow pipe model in relation to zeta values of components. Right now, the parameter fac is used. If we want to use zeta values instead the parameterization of fac needs to be changed for three components. The equation for fac is:
![grafik](https://user-images.githubusercontent.com/26870885/50087133-5ec88a80-01ff-11e9-96af-e17e8f55755e.png)
The components that need changing are:

- Fluid.FixedResistance.HydraulicDiameter
- Fluid.FixedResistance.BaseClasses.PlugFlowCore
- Fluid.FixedResistance.PlugFlowPipe

The changes mainly consist of renaming the parameter fac and adapting its boundaries (e.g. from fac(min=1) to fac(min=0)). The equation for fac needs to be implemented into the HydraulicDiameter component to have access to all necessary parameters (e.g. dpNominal).
Changing those three components will most certainly affect all district heating models. Therefore I want to check with you if you think this idea is worth implementing and which way should be used. I thought of two possible ways to implement it:

1. Delete the parameter fac and replace it by a parameter sumZeta. This improves readability of the code but will affect automated model generation and existing models since parameter naming changes.
2. Use the parameter fac and give the sum of zeta values to it. The equation can be adapted accordingly and compatibility to existing models should be feasible. However, the naming of the parameter is not that clear.

Do you have any thoughts or suggestions on this?

**Comment by MichaMans** [comment]
@MDHering 
Currently I'm not sure if i understand it all right. You already implemented your suggestion and tested it, didnt't you? Where the results better then before? Because this might be a large ajustment to the models of the ibpsa library. Maybe we can go for an implementation suggested with 2. with new models. So not changing the current, more adding new ones to test and discuss them.

**Comment by MDHering** [comment]
@MichaMans I agree that adding new models is probably the best way to compare the two models. The advantage of writing zeta values directly to the pipe model is mainly that this decreases the need for a lot of preprocessing. Zeta values can be taken from literature directly, whereas fac needs to be calculated depending on flow regimes at nominal conditions right now. I will add the new models for a better understanding of the difference between the two, if this is okay?

**Comment by PMehrfeld** [comment]
@MDHering: I just went fast through your text, but if I see it correctly, it might be an option for you to take the model `AixLib.Fluid.FixedResistances.HydraulicResistance`. Here you directly have the parameters `m_flow_nominal`, `diameter` and `zeta`. So you can implement maybe a combination of zetaResis - PlugFlowPipe - zetaResis.

**Comment by MDHering** [comment]
@PMehrfeld Thanks for the advice. Somehow I missed this possibility completely. I will add a model according to your suggestion and test it.

**Comment by MDHering** [comment]
I added my first draft of the PlugFlowPipes to the pipes folder in the disctrict heating folder. The pipes named PlugFlowPipeZeta and StaticPipeZeta use an additonal hydraulic resistance component. With those pipe models a large DH simulation failed during the comilation due to Bad Allocation error.

The model PlugFlowPipeFacAsZeta is modelling additional pressure losses with the factor fac instead of an additional hydraulic resistance component. This seems to reduce the number of equations and allows the simulation model to be compiled even for a large DH network. Addtitional components need to be changed to use this approach. Those components are added to the folder BasClassesPlugFlowFacAsZeta.

@MichaMans Do you think the model PlugFlowPipeFacAsZeta is an approach worth following? Or do you think an approach like PlugFlowPipeZeta is better for large DH networks?

**Comment by MDHering** [comment]
@MichaMans @TobiasBlacha I tried the approach that you suggested to write the calculation of parameter fac in the model generation template. For my first test this works really well. The changes are all part of the uesmodels project (see issue 32).
In my opinion this is a good solution. If you aggree I delete all additional pipe models that I added to this branch, because we do not need them any more.

**Comment by MichaMans** [comment]
@MDHering @TobiasBlacha As fare as i see the progress here, we reached a point in terms of model development which serves first DHC applications. Therefore we should think about merging it to the development. At least we should check the following for that:
- [ ] Check all models in pedantic mode
- [ ] All examples should check and simulate as well
- [ ] maybe integrate some example / reference results

**Comment by MDHering** [comment]
@MichaMans I pushed a first draft of a valvecontrolled Closed Loop substation. This substation is allready optimized to minimize the number of equations and to substitute the secondary fluid flow and Heat Exchanger model. Additionally, a control loop is added to set the opening of the valve according to available heat flow and requiered heat flow.
I sucessfully simulated the small LTDH network. Additionally, I tested the large juelich heating network and ended with the "bad allocation" error during the compilation of the model. To implement the functionality of the closed loop substation into the large network I added the OpenLoop.ValveControlledHX model. This model should yield similar results to the closed loop model with a reduced amount of equations.
I simulated the large network sucessfully with the OpenLoop substations. However, there is still some interesting behavior:
I compared the closed loop model to the open loop model for the small network and a simulation time of one week.
* Results are identical
* Simulation Time:
  * Open Loop: 251 s
  * Closed Loop: 148 s
* Number of Equations:
  * Open Loop: 11514
  * Closed Loop: 13026

**Comment by DaJansenGit** [comment]
Thanks for the work you've put into this so far. Can you give us a short estimation of how much effort is still needed? Do you consider it realistic to close the issue in the near future? Otherwise I would assign it to v0.9.0.

**Comment by MichaMans** [comment]
@DaJansenGit thanks, i would go for v0.9.0. 😃

**Comment by DaJansenGit** [comment]
> @DaJansenGit thanks, i would go for v0.9.0. 😃

Ok, I changed the milestone :) Thanks!

**Comment by KremerMartin** [comment]
@MichaMans As I saw, you are going for v0.9.0. Maybe this could be something for the hackday next week. Otherwise, you can just remove the hackday label. ;)

**Comment by MichaMans** [comment]
@NilsNeuland

**Comment by MartinRaetz** [comment]
Hello everyone,
what is the status of this issue?
Anything we could tackle in tomorrows hackday?
