### ISSUE TITLE
Error while simulating examples

### ISSUE THREAD

**Issue by atharkamal** [RWTH-EBC/AixLib#47]
Dear AixLib team i am having problems while simulating the library examples. Screenshot of the error is attached. 
![error](https://cloud.githubusercontent.com/assets/10814607/6004809/ff4dc04c-ab1e-11e4-8415-d8aeed5130ca.png)

**Comment by marcusfuchs** [comment]
Dear atharkamal, thanks for your interest in AixLib! I am not sure whether the problem you are experiencing is related to the model itself, it might be a problem with your system setup. Have you been able to simulate example models from the Modelica Standard Library? If not, have you set your working directory (In Dymola: File > Change Directory) to a path for which you have write access?

**Comment by atharkamal** [comment]
Thanks Marcus for the reply.

**Comment by atharkamal** [comment]
So Marcus, i managed to get rid of the error above but now i can't access the weather data file. This is the error i am getting. I have tried changing the input location through the parameter settings of the weather model, but can't seem to resolve the issue. Your help is really appreciated.
![error 2](https://cloud.githubusercontent.com/assets/10814607/6015897/9e351efc-ab93-11e4-95f3-d86c3a2ff61b.png)

**Comment by marcusfuchs** [comment]
Hi Athar, I am sure we can fix this:
For the weather file we use the path "modelica://AixLib/Resources/WeatherData/TRY2010_12_Jahr_Modelica-Library.txt". 

modelica:// is a hint for Dymola to look for the local AixLib copy on your system. In order to tell Dymola where to search for AixLib, you need to include the path to your AixLib copy in the Environmental Variable "MODELICAPATH". If you are using Windows you can find more information on setting environmental variables here: http://www.computerhope.com/issues/ch000549.htm
Add the path to your AixLib copy to the value of your MODELICAPATH variable. If your copy of AixLib would be at D:\AixLib, this is the string to add to MODELICAPATH. After a restart of your system, Dymola should be able to find the file and simulate the model.
There is more information on using the MODELICAPATH in Michael Tiller's excellent free book:
http://book.xogeny.com/components/packages/package_def/#modelicapath

**Comment by atharkamal** [comment]
Dear Marcus,
                     I am a student at Masdar Institute and am working on a small part of Annex 60. It will really help me if i can use the AixLib. (PS can you suggest method in creating several different building models/envelops like Commercial,Residential and Office,etc. for energy simulation using the AixLib).

I am still getting the above error. PS this error is occurring in the HighOrder models. If i try to simulate Apartment_VoWo i get this warning(image below) with the error of weather file  or RoomGFOw2_DayNightMode( Similar error to image below but "Not possible to open file "RoomGFOw2_DayNightMode.mat": No such file or directory")
![error 3](https://cloud.githubusercontent.com/assets/10814607/6019632/25d2ffc8-abbc-11e4-90be-da666df4b32c.png)

**Comment by marcusfuchs** [comment]
Thanks for your comments, there seems to be a problem with the relative path. We just merged a temporary fix which sets the examples to use a record from AixLib's database instead of the external text file. So if you pull the current master version, the weather file problem should be solved. 

Regarding the modeling of different building types, the approach depends on whether you want to use the high order or the low order model. We are currently working on a software solution to quickly parameterize different building setups with the low order model automatically, but it will still take us a few months to make that available.

**Comment by atharkamal** [comment]
Thank You Marcus. 
It's working now.

**Comment by marcusfuchs** [comment]
Perfect, you're welcome.

**Comment by atharkamal** [comment]
Hey Marcus....
Thanks again for the help. But just a question. Since you made the change, can i use any other weather data file? And if yes, then how do i convert an epw file to the txt format. 
I can use matlab coding to get a matrix(column) form of data from epw to txt format but am not sure what all the columns represent, cause i couldn't find the TRY standard. Are they anyway related to TRNSYS pattern?

**Comment by marcusfuchs** [comment]
Of course you can use any other weather data you like. The changes we made were intended to have examples that can be run directly. But you can easily change that. Within the weather model, there is a block WeatherData which is nothing else than a standard CombiTimeTable from the Modelica Standard library. We changed that table to use weather data from a database record instead of a text file. Simply remove the modifier which states tableOnFile=false or set to true and specify the path to your table at the parameter fileName. Your weather file must follow the given format of TRY, which is short for test reference year and has nothing to do with TRNSYS. You can see what most columns mean from the tab Optional output vector in the Weather model.
