### ISSUE TITLE
HeatPumpDetailed example broken (in SimulationX)

### ISSUE THREAD

**Issue by ghorwin** [RWTH-EBC/AixLib#544]
Opening and running the example AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed gives the following error:

`In AixLib.Fluid.HeatPumps.Examples.HeatPumpDetailed.heatPump.cycle.Corr_icing: Kann den Wert von "AixLib.Fluid.HeatPumps.Examples._.HeatPumpDetailed.heatPump.cycle.Corr_icing" nicht setzen.
Message: Modelica.ValueNotSet
`

Apparently, the heat pump requires a frost/defrost model and does not have a default model associated.

Suggested fix: set a trivial default model so that the example works out-of-the-box or add/fix the condition to ignore the relevant equations if model is unset.

**Comment by PMehrfeld** [comment]
@ghorwin: Which parameters did you change in the example. To use a correction function for defrosting, the parameter `capCalcType` must be set to 1 (use a polynomial instead of tabulated data).

Anyway, the [default function for `Corr_icing` is set to noModel](https://github.com/RWTH-EBC/AixLib/blob/31bd07b8de6feaa68f2aa2cc66308212bb9ee9c2/AixLib/Fluid/HeatPumps/HeatPumpDetailed.mo#L69). Hereby, the function's output equals 1.

**Comment by PMehrfeld** [comment]
I will close this issue. However, feel free to reopen it again.
