### ISSUE TITLE
Parameter study in OFD (Building Orientation & U-value (wall)

### ISSUE THREAD

**Issue by Amuntaseer** [RWTH-EBC/AixLib#559]
> Just stopping by to let us know about some issue you encountered with AixLib? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new models to AixLib, please make sure to briefly answer the following few questions. For more information on how to contribute to AixLib, see our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?
1) I want to change the building orientation of the OFD model to see the changes in total energy consumption. What components or method can I use to develop the model for analyzing this parameter?

2) I have already studied the effect of changing the U-value(Window), to analyze the total energy consumption. But in order to change the U-value for the OutsideWalls there is no direct option. The different wall layers also does not contain the U-value. What can be the solution regarding this issue?(OFD)
## Why do we want to solve it?

- I can develop the OFD model where the parameter "Building Orientation" and "U-value(Walls)" can be studied.

## How do we want to solve it?

- ...
@PMehrfeld

**Comment by Amuntaseer** [comment]
Hello Mr.Philipp,

I am doing my master Thesis in Gas Und Wärme Institute, Essen.e.V.  For my
Thesis work I am working with the OFD from AixLib. In order to perform some
simulations with different Parameters I Need some assitance through GitHub.

Best Regards,
Adnan

**Comment by PMehrfeld** [comment]
Many thanks for your background information. I'm glad that you are using the OFD models from our AixLib.
I can give a possible solution or at least an approach for both of your questions:

1. The orientation only affects the solar irradiation. Thus, you could add new records (while extending the base class `AixLib.DataBase.Weather.SurfaceOrientation.SurfaceOrientationBaseDataDefinition`) and fill in your `Azimut`s and `Tilt`s like in the records in the same sub package. Don't forget to select the correct record in the weather model:
![image](https://user-images.githubusercontent.com/11769433/39310038-b245e2ec-4969-11e8-8861-10817a90d512.png)

2. You should revise the selected wall records for the outside wall. Which one is chosen depends on the parameter TMC (Thermal mass class) and TIR (Thermal insulation regulation). All rooms in the package `AixLib.Building.HighOrder.Rooms.OFD` decide via if-else-statements based on TMC and TIR which record is used. Look for the parameter `Type_OW` (Type Outer Wall) in each of the rooms. Change for example the thickness `d` and/or the thermal conduction coefficient `lambda` such that your desired U-value is achieved.

Thanks again for using the AixLib! However, I would kindly ask you to not see us as a support service for energy engineering questions. I am pretty sure, you can identify the dependencies of energy related processes in a building by yourself, since this is probably part of your thesis :)

**Comment by AnaConstantin** [comment]
@Amuntaseer I think is great you opened the discussion hier on GitHub as well. However as we have already discussed some of these aspects per Email already I think it would be good to include those answers here as well as it would move the discussion further along.

**Comment by PMehrfeld** [comment]
@Amuntaseer : Were the suggestions for solving your problem helpful? If there are no more questions, please close this issue :)

**Comment by Amuntaseer** [comment]
Thank you, the suggestion was very helpful to solve the problem.
