### ISSUE TITLE
 Windows command line for Dymola Python Interface

### ISSUE THREAD

**Issue by nariday** [RWTH-EBC/AixLib#584]
Hi! 

I'm following the instruction for [Dymola Python Interface](https://github.com/RWTH-EBC/AixLib/wiki/How-to:-Dymola-Python-Interface#installing-the-python-package-dymola). I am stuck in the line where it states:

> The recommended way to use the package is to append the \Dymola 2018\Modelica\Library\python_interface\dymola.egg file to your PYTHONPATH environment variable. You can do so from the **Windows command line** via set PYTHONPATH=%PYTHONPATH%;D:\Program Files (x86)\Dymola 2018\Modelica\Library\python_interface\dymola.egg. 

Could you explain what exactly "Window command line" means? Do I need to pull out the cmd from my Windows 10, and just type that in? (Nothing happened when I did.) Or does it mean the command line of some software--e.g., MS Visual Studio? 

I found [this video](https://www.youtube.com/watch?v=dU_ca27EGT8), but still I don't think this installed dymola package..

Thank you,
Nari

**Comment by marcusfuchs** [comment]
@nariday Yes, it just means to hit your windows key, type `cmd`, Enter and type that in. In the command line, you will not see any returned values. Please note that this does not "install" the dymola package in the same way that e.g. pip installs packages. It just adds your Dymola path to an environment variable called `PYTHONPATH` to tell Python where to look for a package called `dymola` after it will not have found it in your actually installed packages.

**Comment by nariday** [comment]
@marcusfuchs Thanks a lot for your reply! I followed the instruction, but unfortunately I still don't see that `dymola` is successfully called. 

So in the Command Prompt, it started with `C:\Users\me>` and then I typed the `set...` part as below:
`C:\Users\me>set PYTHONPATH=%PYTHONPATH%;C:\Program Files\Dymola 2018 FD01\Modelica\Library\python_interface\dymola.egg`

Then in the python shell, I tested with this line, 
`from dymola.dymola_interface import DymolaInterface`
which ended up with this screen,
![image](https://user-images.githubusercontent.com/23063385/43730899-df21adbc-997a-11e8-945a-239a8d271bcd.png)

Is there some mistake I made? I also tried to connect python with JModelica and OpenModelica for many days, but I seem to have the similar issue with each one of them. 

Any advice would be greatly appreciated!

**Comment by marcusfuchs** [comment]
@nariday It's hard to tell for me where the problem is. Did you check that your Dymola installation is actually at `C:\Program Files\Dymola 2018 FD01\` as you set in the path above? Apart from that, I am not sure how to help any further. Maybe you could contact your Dymola support?

**Comment by PMehrfeld** [comment]
1. I am pretty sure that Dymola 2018 FD01 comes along with python 3, but you have python 2.7.14 (see your screenshot). However, the thrown error is not due to this fact.

2. When you set the PYTHONPATH environment variable vie `cmd` it is only temporarily for this special shell session. Did you execute all commands in one shell session? Like in the screenshot below.

3. However, it might be smarter to permanently set the environment variable PYTHONPATH. 
- Press the Win button on your keyboard and search for "environment variable" (or german "Umgebungsvariable") and press Enter.
- If a variable PYTHONPATH already exist, append `;C:\Program Files\Dymola 2018 FD01\Modelica\Library\python_interface\dymola.egg`. If not, create a new one, call it `PYTHONPATH` and give the value `C:\Program Files\Dymola 2018 FD01\Modelica\Library\python_interface\dymola.egg`.
- Then the python import statement `from dymola.dymola_interface import DymolaInterface` should succeed (but please make sure to use a python 3 kernel).

![unbenannt](https://user-images.githubusercontent.com/11769433/43762200-91d336cc-9a27-11e8-9920-8e83d1a52a6e.JPG)

**Comment by nariday** [comment]
@marcusfuchs @PMehrfeld  Thanks, both, for your help! Setting the PYTHONPATH solved the problem. 

Regarding Python 2.7, I remember that Python 3.x didn't work for some FMI-related work a year ago, so I had to uninstall the v3 and reinstall 2.7 back then. But I'll definitely check if that constraint still exists, and will update it to python 3. Thanks a lot for your tips!
