### ISSUE TITLE
Adaption of modular CHP from Fluid to FastHVAC 

### ISSUE THREAD

**Issue by nhuelsenbeck** [RWTH-EBC/AixLib#684]
**What is the problem?**

A version of the CHP model developed by JulianMatthes needs to be integrated into the FastHVAC library for performing time-saving calculations.

**How do we want to solve it?**

This issue is based on issue #667. Adaption can be divided into the following actions:
- Change Fluid ports to enthalpy ports
- Change parts from Fluid library (e.g. Closed Volume)
- Remove all pressure dependencies

**Comment by KremerMartin** [comment]
@Dawac What is the current status of this issue? Could this be something for the hackday next week?

**Comment by DaJansenGit** [comment]
@KremerMartin Actually during the conversion of the model we figured out that the used approach of the Fluid CHP model doesn't fit the approach of the FastHVAC. Due to this reason we stopped working on this. 
I will have a look at this on hackday and decide whether we delete the branch or finish it.

**Comment by DaJansenGit** [comment]
This will be closed now because the usage of the very detailed CHP model in the fasthvav is questionable.
