### ISSUE TITLE
Adapting Multizone models to new TEASER version

### ISSUE THREAD

**Issue by nhuelsenbeck** [RWTH-EBC/AixLib#690]
**What is the problem?**
The new version of TEASER exports specific numbers in W/m^2 for internal gains coming from persons and machines respectively.
This issue is related to https://github.com/RWTH-EBC/TEASER/issues/567

**How do we want to solve it? Describe the solution you'd like**
The models ThermalZone and ThermalZoneEquipped include three models for internal gains calculation that need to be changed:

- HumanSensibleHeat_VDI2078
Duplicate and adjust

- Machines_DIN18599
Duplicate and adjust

- Lights_relative
Rename

**Comment by DaJansenGit** [comment]
This is done with the Merges of #691 and RWTH-EBC/TEASER#568.

**Comment by KremerMartin** [comment]
@DaJansenGit  The new human model does not consider the influence of the room temperature on the heat output of the humans inside. The old model does consider this. I think we should rework the new model.
Moreover the old model cannot be used without modification, since the zone params do not contain the number of people anymore.
I will reopen the issue. I can assist you. 
@MartinRaetz Maybe this is also interesting for you.

**Comment by DaJansenGit** [comment]
@KremerMartin we are aware of this. But due to the fact, that we don't have any data for the temperature dependence on the internal gains we removed the influence in the new model which is now the default model in TEASER.

**Comment by MichaMans** [comment]
@DaJansenGit @KremerMartin @MartinRaetz @PRemmen 
Maybe we can integrate some kind of support for the temperature based on the "old" tables. I would not link that to TEASER but i would suggest to implement some kind of converter model between the old and the new approach.

**Comment by KremerMartin** [comment]
@DaJansenGit @MichaMans 
The new VDI 2078 provides equations for the temperature dependency based on the room temperature. I think it would be easy to implement these equations in the new human model.
For me it looks like we multiply a schedule with a heat flux (parameter). Later on we divide the Heat through a heat flux per person. Would it not be easier to provide heat flux data per person in the human model and multiply it with a factor person/m²?
I am not an expert for TEASER. Is TEASER providing heat flux data (W/m²) or is it providing data like 0.2 persons/m²?

**Comment by AnaConstantin** [comment]
Although no one asked for my opinion, I feel compelled to give it, since I once build an Archetype in TEASER for a retail store. And I had to change the internal gains models in AixLib and also the xml data for TEASER to better suite the standards I found (which refered to Germany and the UK). I am of the opinion that persons / m2 is a better way of characterizing occupants for a designated type of zone. The old internal gains for people had this dependency on temperature, however several other standards (ASHRAE and DIN) do not have this dependency, so I'm not sure we need it as long as we do not consider moisture output. I also changed a bit the structure of the ThermalZone model : Envelope + Internal Gains + Energy System + Control and propagated all this changes through TEASER and the generated templates. I am more than happy to share this with you all before I leave and I think it's doable in half an hour. I have a feeling @KremerMartin might be moving in a similar direction and I hate the thought of "doppel Arbeit". Everything was done in a TEASER fork, to which at least @DaJansenGit should have access to.

**Comment by KremerMartin** [comment]
@AnaConstantin Thanks for sharing your experience. I am aware of the fact, that only the VDI 2078 provides dependency on the temperature. As I am working on a human model providing moisture output, I am applying the temperature dependency as it has huge influence on the moisture output. Nevertheless we could ignore the temperature dependency on the heat output in the new specific human model. I am also of the opinion that persons/m² is better than W/m². @DaJansenGit Maybe you can tell me where to find the fork or give me access. I am also no fan of "doppel Arbeit".

**Comment by DaJansenGit** [comment]
@KremerMartin
TEASER provides the data directly in the form it was given by SIA and DIN as W/m². 
I have only developer access to the fork, @AnaConstantin is the only maintainer (except moritz), so she needs to give you access.

> For me it looks like we multiply a schedule with a heat flux (parameter). Later on we divide the Heat through a heat flux per person.

That's not the case. We use a given heatflux per m² room area and multiply it with the area of the zone (and the schedule of course), that's all. The reason why @MartinRaetz and me did this re-modelling is, that we think that for the non archetype TEASER buildings the way of W/m² is a better way. The persons/m² lead often to faults in the simulation, because the user had to estimate and input the data how many people are in the respective zone. With the W/m² approach the internal gains are scaled automatically by the existing usage conditions.

**Comment by KremerMartin** [comment]
@DaJansenGit Thanks for response. If DIN and SIA provide data in W/m², I agree with you, that we should not mess with more calculations. In my opinion we should nevertheless re-apply the number of people to the zone parameters, so that a user is able to use the old human model without having to change the default zone params. (backward compatibility) Or we should add a parameter in persons/m² and change the old human model using the persons/m² parameter. This could be easy done using the W/m², the zone area and the mean W/person. It is just one equation, as I see it.

**Comment by AnaConstantin** [comment]
After talking to @KremerMartin and looking into the norms, I think we can re-discuss this W/m2 vs person /m2.
Both SIA 2024 (Ausgabe 2006) and DIN 18599 give as a starting point persons /m2 (SIA actually m2/person) and calculate W/m2 using a type of activity (DIN) or a formula (SIA). SIA takes in consideration the temperature of the room for the heat output of persons, it also calculates output. VDI 2078 now gives formulas instead of tables to calculate the heat and moisture output depending on activity type.
For me it makes sense to have heat output depending on temperature. My suggestion is this: type of zone -> occupants density. type of activity -> heat output / person. Heat output can be dependent on temperature (true/false boolean).

**Comment by MichaMans** [comment]
@PRemmen @AnaConstantin @KremerMartin @DaJansenGit @MartinRaetz

**Comment by MichaMans** [comment]
@AnaConstantin @PRemmen @DaJansenGit @MartinRaetz @KremerMartin 

As we discussed earlier today, i try to sum up the discussion (nothing is fixed yet, so still in discussion):

1. @KremerMartin will provide the actual formula or a sketch of the input and outputs of the new formula provided by the VDI 2078. This should be our reference and the goal of implementation
2. we need to discuss the adjustments of TEASER to achieve these goal, mainly by providing all inputs, required by the formula of the VDI 2078. The related discussion is [here](https://github.com/RWTH-EBC/TEASER/issues/567).

**Comment by KremerMartin** [comment]
@AnaConstantin @PRemmen @DaJansenGit @MartinRaetz @MichaMans 

Here is the formula to calculate the heat output depending on the design room temperature and the activity level as provided in the VDI 2078. 
![VDI2078_Waermeabgabe](https://user-images.githubusercontent.com/48821826/57777935-4d8a9800-7723-11e9-94ef-c1883cc78c62.JPG)

The definition of the activity levels (4 instead of the original 3 ones) can also be found in VDI 2078.
![VDI2078_Aktivitaetsgrade](https://user-images.githubusercontent.com/48821826/57777984-6abf6680-7723-11e9-9e94-b068ca7407e5.JPG)

Maybe we can discuss in which way we would like to implement the activity levels, since a simple if-clause would not deliver values, if the activity level lies in between the given levels.

**Comment by MartinRaetz** [comment]
Please see my concerns issued here: https://github.com/RWTH-EBC/TEASER/issues/567#issuecomment-492648593

**Comment by DaJansenGit** [comment]
how to proceed: 
We note in the documentation that there is no backward compability

**Comment by MichaMans** [comment]
and we need a new major release 😄

**Comment by DaJansenGit** [comment]
The necessary changes in TEASER and AixLib are done. We are waiting now for the release of the json update #584.
For more information please see https://github.com/RWTH-EBC/TEASER/issues/567

**Comment by KremerMartin** [comment]
@DaJansenGit We will need to rework our internal gain models containing moisture output. The input connector of the RC was changed to `QLat_flow` instead of `mWat_flow`. The mass flow rate of moisture is now calculated in the RC model using the enthalpy of evaporation. So we will need to provide the moisture output of our internal gain models using the latent heat of the moisture content. This will reduce the complexity of our models and should be done easily.
I will tackle that as soon as the changes are merged into the IPBSA master, as I do not want to rework it twice anymore.

**Comment by KremerMartin** [comment]
Has been solved by PR #815
