### ISSUE TITLE
Add Moisture Balance to Thermal Zone

### ISSUE THREAD

**Issue by KremerMartin** [RWTH-EBC/AixLib#695]
**What is the problem?**

The Thermal Zone only contains a balance for thermal loads. As I am doing research on Moisture Recovery, I find it useful to have an moisture balance in the thermal zone.

**How do we want to solve it? Describe the solution you'd like**

I am setting up new reduced order models, that differ in the air volume. Instead of using the mixing volume, I will be using the mixing volume moist air. This will ensure that existing models based on the existing reduced order models are not influenced by this change. Moreover the simulation time will not be enlarged for those, who do not need an moisture balance.

I will define internal gains for moisture depending on VDI 2078. Moisture input through walls will in a first approach be neglected.

**Describe alternatives you've considered**

I first considered changing the reduced order models directly. Therefore I wanted to bind the moisture balance on an if-clause using a boolean variable as it is done in the MixingVolume (use_m_wat_flow).
As the simulation time increases even if the boolean variable is set to false, I discarded this idea.

**Comment by mlauster** [comment]
A third way could be to use the replaceable construct to extend the existing models, this should avoid longer simulation times.

**Comment by KremerMartin** [comment]
@mlauster Thanks for that advise. I'll consider that. If I can manage it that way, it would be the smartest way, I think.

**Comment by KremerMartin** [comment]
There is still an error, when checking the new ThermalZoneMoistAir model. The check fails for the connector mWat_flow. But it is connected. I will check this. When setting up a simulation, the error does not occur.
![bug_modelica](https://user-images.githubusercontent.com/48821826/55622274-044c3d80-57a0-11e9-9bc9-20545333ef3d.JPG)

**Comment by KremerMartin** [comment]
Check of ThermalZoneMoistAir is now working. Problem was the conditional removal of the internal gain human if ATot =0. Now the connector mWat_flow in the ROM is also depending on this condition. This solves the structural singulatrity for ATot =0.

**Comment by AnaConstantin** [comment]
@KremerMartin I also added a VolumeMoistAir in a simple room as part of branch #520 . There is a branch
https://github.com/RWTH-EBC/AixLib/tree/issue520_PnH. I implemented the infiltration in the wall and then because of the project requirements a ventilation also in the facade (AixLib.PlugNHarvest.Components.Walls.Wall). I consider ventilation and infiltration using fresh air (done after the examples in the Buildings Library). Have a look if you are interested, and let's meet up, ma
ybe we can find a joint solution, so there aren't big differences between models.

**Comment by KremerMartin** [comment]
@AnaConstantin Thanks for your comment. I like your infiltration model for the wall component. 
As I am working on the reduced order model, I extended a new VarAirExchange model to depict the humidity infiltration. (For this reason I do not need a connection to the fluid ports.) So I don't know whether there is much overlapping between the two cases.
Maybe you will find my new human model (HumanTotalHeat_VDI2078) in the internal gains helpful. If I get it right, you are using a constant humidty output of the persons for your issue #520. I enhanced the human model by adding a table for the humidity load as depicted in the VDI 2078. What could lead to problems is the fact, that the temperature will decrease when adding water (the MixingVolumeMoistAir assumes adiabatic humidification). For this reason I added a latent heat flow in the new HumanModel.

**Comment by KremerMartin** [comment]
This Issue has been solved. Since the changes made here are connected with issue #690 we are waiting now for the release of the json update in TEASER [#584](https://github.com/RWTH-EBC/TEASER/pull/584).
For more information please see [RWTH-EBC/TEASER#567](https://github.com/RWTH-EBC/TEASER/issues/567)

**Comment by DaJansenGit** [comment]
@KremerMartin Sorry for the confusion, but did you already implement the needed values for moisture gains by plants in the models and the records?

**Comment by KremerMartin** [comment]
@DaJansenGit Until now there is a model for internal moisture gains from e.g. plants using a parameter _specificMoistureProduction_ in g/(hm²). This needs to be implemented into the records. I can easily implement it on Modelica-Side and connect it to the model.

**Comment by DaJansenGit** [comment]
@KremerMartin as discussed, we should change the name of the modelica parameter from
`internalGainsMoisture` to `internalGainsMoistureNoPeople`

**Comment by DaJansenGit** [comment]
@KremerMartin the tests for the thermalzone examples fail. 
[log](https://git.rwth-aachen.de/EBC/EBC_all/github_ci/AixLib/-/jobs/475757) 
Could you please have a look at this, because it's related to your integration of the parameters `X_w`  and `volAir.mWat_flow`. For simpler testing you can just test the examples in Aixlib/AixLib/ThermalZones/ReducedOrder/Examples

**Comment by KremerMartin** [comment]
@DaJansenGit Thanks for the hint. I did not recognized that. I have changed the OneElement RC. The volAir is now conditioned on the parameter `use_moisture_balance`.

if `use_moisture_balance` is _false_ (default) then the normal volAir will be used. If it is true, a the volMoistAir will be used.

**Comment by KremerMartin** [comment]
Changes on ROM will be, if approved, implemented in the IBPSA (see issue [1209](https://github.com/ibpsa/modelica-ibpsa/issues/1209)) to avoid merge-conflicts.

**Comment by mlauster** [comment]
@KremerMartin, did you change it in a dedicated copy of RC.OneElement or directly in the original model? In the latter case, you need to propose the changes to the IBPSA core lib. Otherwise you will get conflicts when merging the core lib next time. By the way, there is an issue concerning latent heat gains in the RC models in the buildings lib. It might be with connecting with them to refactor the OneElement model in a joint attempt.

**Comment by mlauster** [comment]
Ah, sorry, too late, you already answered my question

**Comment by KremerMartin** [comment]
@mlauster Thanks for the hint regarding the buidlings lib. I will have a look at that.

**Comment by KremerMartin** [comment]
@DaJansenGit After recieving answer from M. Wetter, I pushed my changes just now. We are now ready to do the pull request in this branch. I adapted the changes on the internal gain models right here, since the branch to this issue was more ahead than the internal gain branch.

**Comment by KremerMartin** [comment]
closed by PR #815
