### ISSUE TITLE
Again with The unit test

### ISSUE THREAD

**Issue by AnaConstantin** [RWTH-EBC/AixLib#697]
**What is the problem?**
As previously stated in #63 we need unit tests. 

**How do we want to solve it? Describe the solution you'd like**

Implement some tests including reference results. Test it with CI.

**Describe alternatives you've considered**

Check what using the ModelManagement Library can also do.

**Comment by MichaMans** [comment]
Also related to #416

**Comment by AnaConstantin** [comment]
I did some reading on https://github.com/ibpsa/modelica-ibpsa/wiki/Unit-Tests and the following things are important:
1. The example in the library and the script (Resources/Scripts/) have to have the same startTime, stopTime and tolerance ( and anything else that was set differently than the default such as the solver).
2. Tolerance and stopTime have to be different than the default values, as they need to be explicitly written in the annotation. Tolerance mus be lower than 1e-006 (1e-004 default für dassl and Lsodar)
3. In the IBPSA library the default value "500" for number of intervals is used, instead of outputInterval.
4. Reference results are produced / compared only for the plots in the script, under Resources/ReferenceResults.
5. When providing new examples do not forget to commit the reference results.

**Comment by MichaMans** [comment]
@AnaConstantin 
I already tried to generate some reference results following the description above, but i did not manage to get this working. Were you able to generate these?

**Comment by AnaConstantin** [comment]
@MichaMans for IBPSA yes (had to set the DYMOLAPATH on PATH as well).
By doing this:
>>> import os
>>> import buildingspy.development.regressiontest as r
>>> rt = r.Tester(tool = "dymola")
>>> myMoLib = "D:\Git\Modelica\AixLib\AixLib_issue697\AixLib"
>>> rt.setLibraryRoot(myMoLib)
>>> rt.run()
it's now running on AixLib but it will take a while until it's done. I deleted all the reference results so I expect new ones to be written.

**Comment by AnaConstantin** [comment]
Worked! Execution time = 4626.670 s on 4 cores on a very old laptop. Saved the log file.

**Comment by MichaMans** [comment]
- [ ] create new branch for ci integration
- [ ] merge the actual ibpsa library WITH all result files in the branch
  - [ ] Include this feature to the buildingspy package
- [ ] Inlcude the gitlab-ci.yml file for each package
- [ ] Integrate some kind of coverage result @AnaConstantin could you please check your logs if you find some information there

--- 

- [ ] Integrate new scripts for model not tested yet
- [ ] generate new results for these models


---

- [ ] integrate all test from modelica-buildings library (maybe jmodelica, html checks etc)

**Comment by AnaConstantin** [comment]
Statistics:
Number of models that failed check                           : 33
Number of models that failed to simulate                     : 34
Number of models that failed to export as an FMU             : 26
Number of models with unspecified initial conditions         : 1

Script that runs unit tests had 51 warnings and 149 errors.
more details in 'simulator-dymola.log'
Looks good.

**Comment by MichaMans** [comment]
@AnaConstantin Can we use these informations to get some sort of coverage? Because at the moment it does not state how many models don't have simulation scripts etc

**Comment by MichaMans** [comment]
@AnaConstantin if you have a look at the last commit with the red cross and look on the details of the gitlab-ci, you can see that 4 out of 9 package test are passing. So there is still some work for the other to run.
Possible failures are:
* Your mentions above (startTime etc are not set equally in script and model) (e.g. for the Systems package)
* The package does not have any test scripts (Electrical / FastHVAC)
* Maybe we'll find some more

**Comment by MichaMans** [comment]
@AnaConstantin @PMehrfeld @mlauster @PRemmen @DaJansenGit @SvenHinrichs 
# Summary / Wrappin it all up
Here, i quickly want to summarize the current state and first implementation of the CI testing of the AixLib with dymola

## Current status of work
We are almost done; The whole testing procedure is already running, currently we do have mainly two open points:
- Waiting for the [buildingspy](https://github.com/lbl-srg/BuildingsPy/issues/253) responding to the issue and if a merge into the master is feasible (act accordingly to the outcome of discussing there)
- Integrating tests for not tested examples (but this can be discussed if it needs to be resolved now):
  - if not, we can exclude FastHVAC and Electrical from testing, because no testscripts are existing there; Systems can be resolved, and for Fluid i think we need to add some reference files, (so nothing magical here)

## Manual / How to 
So for the future, i'm going to provide the documentation of @SvenHinrichs in a wiki page. As soon this is ready (so hopefully next week or this evening) please remember me if i miss that

## Credits
As this is quite a huge milestone we finally reached after 1.5 years ago raising this #416 issue, i want to thank you @all who took part on this. So thank you @SvenHinrichs for your awesome work bringing light to the dark in the whole dymola docker and gitlab ci workflow world! Thanks @AnaConstantin that you committed on bringing this live and up again and thanks in advance for writing additional tests :smiley: Thanks @PMehrfeld for always remembering that this is necessary and a good addition and of course thanks to @mlauster @DaJansenGit @PRemmen for your input on the whole CI topic.

**Comment by PMehrfeld** [comment]
Thanks all for achieving this "huge milestone" (in the words of @MichaMans)!

@FWuellhorst and me will take care of the init issue mentioned above:
> Systems.HeatPumpSystems.Examples.HeatPumpSystem lacks of specified initial conditions (Dymola can resolve that, but that leads to failing tests @PMehrfeld maybe you can have a look at that?)

**Comment by AnaConstantin** [comment]
@MichaMans, the log I get when running runUnitTests.py from BuildingsPy once is the same that we get with the test_overall_coverage, so I'll just use ci/gitlab logs. There seem to be some problems with ascii characters is some tests (e.g. test_dymola_systems), which I do not know what they mean. The rest of the outputs I understand and can work with.

**Comment by MichaMans** [comment]
@AnaConstantin I implemented the coverage and an example is shown below. The examples which are not tested are readable in the log. Regarding the ascii errors, i'm not sure if we really have some ascii problems. The problem with the systems package test should be the missing parameters as described above. But correct me if i'm wrong.

**Comment by AnaConstantin** [comment]
@MichaMans, yes, these are the logs I was referring to. 
I just ran test_dymola_Fluid and got the following error
![image](https://user-images.githubusercontent.com/8265208/55469473-e1862180-5605-11e9-8793-7ff286de610c.png)

**Comment by PMehrfeld** [comment]
As an addition: The following standard might be helpful:
[**ISO/IEC/IEEE 29119 Software Testing**](https://en.wikipedia.org/wiki/ISO/IEC_29119)

**Comment by PMehrfeld** [comment]
@MichaMans : All missing initial value warnings should be gone with latest commits.

**Comment by MichaMans** [comment]
Awesome! The thing is merged! I will close this issue and open a new one for enhancement of unittests
