### ISSUE TITLE
Error: AixLib.Utilities.Interfaces.HeatStarComb has the same name as its type AixLib.Utilities.Interfaces.Star

### ISSUE THREAD

**Issue by dianavaz** [RWTH-EBC/AixLib#698]
Hi!
I'm building a model to simulate thermal loads in a room using AixLib components on OpenModelica. However, when I check the project the following warning message arises:

Component Star in env: AixLib.Utilities.Interfaces.HeatStarComb has the same name as its type AixLib.Utilities.Interfaces.Star.
        This is forbidden by Modelica specification and may lead to lookup errors.

Tried to check some of AixLib's examples such as OFD_1Jan ans OFDHeatLoad and I get the same warning message. For all these cases, an error occurs while flattening the model which I suspect to be related with the former warning.

**Comment by PMehrfeld** [comment]
@dianavaz : Thanks for reporting.
I changed it in branch `issue698_HeatStarComb` and will merge it in the next minutes into the `development` branch (not `master`!).

Since the development was already one version higher than master, I fixed this bug from development.

Furthermore, the line 

`connect(thermStarComb.Star, star);`

in class `AixLib.Utilities.Interfaces.Adaptors.HeatStarToComb` did not change automatically to `connect(thermStarComb.rad, star);` (probably due to not sticking to Modelica Specs). Thus, I did this manually. 

I raised the AixLib's version number and added a conversion script.

**Comment by PMehrfeld** [comment]
@dianavaz : Sorry that this issue ist still open.
But we came across some further problems with renaming instances, which leads to a lot automatic refactoring in a library.
Currently, I am still waiting for an answer from Dymola support. Hopefully within the next week we can merge this branch and close the issue.

**Comment by PMehrfeld** [comment]
@dianavaz : The fix is now merged into our `development` branch. It'll be merged into `master` branch with the next release probably.
Feel free to reopen this issue, if it does not work with current `development`.
