### ISSUE TITLE
Error in Pipe with nParallel

### ISSUE THREAD

**Issue by alexanderAKU** [RWTH-EBC/AixLib#730]
**Describe the bug**

The model Pipe (Fluid.FixedResistences.Pipe) has the option to model multiple parallel pipes with the parameter nParallel. However, the parameter is not included in the heat transfer.
Thus the heat loss for one pipe and multiple parallel pipes is nearly equal.

**To Reproduce**
1. Go to 'Fluid.FixedResistences.Examples.Pipe'
2. Simulate with nParallel = 1 and nParallel = 2
3. Plot fixedTemp.port.Q_flow

**Comment by alexanderAKU** [comment]
- [ ] I will insert the nParallel parameter in the heat resistances.
- [ ] Additionally, I will remove the fluid ports and extend the pipe from PartialTwoPort

**Comment by AnaConstantin** [comment]
Hi @alexanderAKU, thank your for pointing this out. It's not an "accidental" error, as the model was initially developed for a discretised pipe in the length (had this name as well), this is why the nParallel parameter in the insulation and the pipe wall is set to 1. I now see how keeping the nParallel parameter on the upper level and not mentioning this in the documentation was not a good idea. 
My suggestion would be to go a different way: delete the nParallel parameter from the upper level so no one is tempted to use it. Just set an array of pipes: pipe[n], when you need them. In this way you do not have to change anything in the model. Otherwise you might have to write some equations to correctly connect  the heat transfer coefficients, and they might turn out to be a lot of equations.
As the Modelica.Fluid.Pipes.DynamicPipe Model, nested inside this model is at some point also extended from a PartialTwoPort (Modelica.Fluid), an additional extension might lead to some problems. I do not think an extension is needed in this case.
