### ISSUE TITLE
High order examples: Division by zero in pipe

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#76]
When trying to simulate the high order building model's examples RoomGFOw2 and Appartment_VoWo, simulation fails because the static pipe model divides by zero with lambda2 = 0. 

This seems to be a problem with the pipe rather than with the high order examples. For a quick solution, I suggest to replace the static pipe in the examples by the pipe model from MSL.

For the future development an important question is whether to revise the models Pipe and StaticPipe or replace them systematically by other pipe models (from Annex 60 or MSL, for example).
What do you guys think @mlauster, @PRemmen? Others' input is also very welcome of course!

**Comment by mlauster** [comment]
Your quick solution sounds good.
Regarding further development, I think we therefore need to compare the AixLib and Annex60 pipe models and decide what are the best models in our context, e.g. accuracy vs. simulation time. If the Annex60 models win, I'm fine with a replacement.

**Comment by marcusfuchs** [comment]
I think you are right about the need to test the models. One crucial dimension in addition to accuracy (which will not be easy to evaluate) and simulation time seems to be the inherent instability of the AixLib pipe at lambda2 = 0. I am not sure whether we want to put in too much effort to solve that when there are other pipe models that might be more stable already.

**Comment by PRemmen** [comment]
I agree to have a benchmark and then decide how to proceed. In principal I'm totally okay to replace our models with the models from Annex 60. Nevertheless sometimes it might be sensefull to keep both (e.g. if AixLib model shows considerable simulation time advantages, having a good stability at the same time)

I think in we could define a general workflow for benchmarking doubled models, since there are a lot of them (Valves, Boiler, Pump, Radiator etc.)

**Comment by AnaConstantin** [comment]
When I first build the models they worked under the simulation set up. I suggest that we always test the examples before accepting pull requests in order to identify such problems quicker. Until the unit tests are ready, a simple script might be sufficient. 
However, as clearly stated in the documentation of the examples, they are only meant to show exemplary how such a simulation model (building + hydraulics) can be designed and set up. They are not robust models meant for longer or more complex simulations. So to my mind we should just make sure our examples work just the way they are set up, just like the MSL examples. 
Using Annex60 or MSL models and benchmarks is a good idea and I suggest opening another issue for it in order to decide how much we want to go into building complex hydraulic systems, what we want to achieve by this and what models are we going to use to this purpose.
I can get the models running again with the current models and build a quick script for testing these examples before each pull in order to close the issue, if you are ok with this.

**Comment by marcusfuchs** [comment]
Thank you Ana for your input - I very much agree that we ought to test these things before pull requests. I am pretty sure I introduced the problems myself with the conversion to Annex 60 base classes and it did not catch my attention back then. Also, I agree that the example should only demonstrate the general functionality, so the main idea is that they are executable, which currently is not the case unfortunately. 
For the BS 2015 paper I already reworked the example to run again in a local branch. If you have not done any work on this, I suggest I clean up my proposal and it would be great if you could look over it then and give your feedback. It will take me a few days until I have time to so, though.

**Comment by psteinhoff** [comment]
I know i am not that deeply involved in that modelica stuff, but as a kind of suggestion how to proceed with "new code" in github.
My understanding was:
- create a branch as a copy of i.e. AixLib->master with a representative name like fix#76 or similar
- do your work on that branch, perform a lot of commits to track your changes properly
- create a pull request for your branch (pull request do not have to be merged directly)
- discuss your pull request with others, if necessary modify your branch (other users can do this too, by forking your branch) 
- after a decision period of time X merge the pull request into master

If you are already familiar with that procedure please excuse my spam...

**Comment by PRemmen** [comment]
Thanks for the comment. I think the general "git workflow" is clear and also available in our wiki. More or less we are following that. Few weeks ago we had a kind of big pull request that basically changed the whole structure of the AixLib, so we simply overlooked the mistakes mentioned above :)

**Comment by marcusfuchs** [comment]
see #134

**Comment by marcusfuchs** [comment]
This is obsolete
