### ISSUE TITLE
Add an enhanced PVSystem model

### ISSUE THREAD

**Issue by arnoldfuetterer** [RWTH-EBC/AixLib#767]
A Model that determines the DC performance of a PV array will be added. The model will introduce dependencies of the I/V-characteristics and the celltemperature of the array.

**Comment by arnoldfuetterer** [comment]
Current Branch: issue767_NewPVSystemModel
Progress so far:
- A PVSystemDC model was added to the PVSystem pacakge
- weather bus (as used in PVSystem TMY3) is now used as input instead of a few singel inputs
- variable description of groRef was moved from code to documentation of ExamplePVSystemDC
- submodels are now described in documentation of ExamplePVSystemDC
- a default PV module record was chosen (QPlusBFRG41285)

ToDo:
- validate functionality of the model
- delete records, weather data and models that are not used or necessary
- compare "PVBaseRecord" and "PVBaseRecordNew" and only use one (make necessary adjustments)

Bugs:
- DCOutputPower has some negative values (using "USA_IL_Chicago-OHare.Intl.AP.725300_TMY3" as weather data input )

**Comment by arnoldfuetterer** [comment]
The mentioned bugs are fixed and the results are the same as in the model from which i started to make changes.

**Comment by LauraMaier** [comment]
Current Branch: issue767_NewPVSystemModel
Progress so far:

A PVSystemDC model was added to the PVSystem pacakge
weather bus (as used in PVSystem TMY3) is now used as input instead of a few singel inputs
variable description of groRef was moved from code to documentation of ExamplePVSystemDC
submodels are now described in documentation of ExamplePVSystemDC
a default PV module record was chosen (QPlusBFRG41285)

ToDo:
- [x] validate functionality of the model

- [x] delete records, weather data and models that are not used or necessary
- [x] compare "PVBaseRecord" and "PVBaseRecordNew" and only use one (make necessary adjustments)

Bugs:
- [x] DCOutputPower has some negative values (using "USA_IL_Chicago-OHare.Intl.AP.725300_TMY3" as weather data input )
- [x] DCOutputPower is lower in summer compared with winter. There might be something wrong with the input (see connection of weather bus)

Bugs were solved

**Comment by XucYin** [comment]
@LauraMaier What is the current status of the issue? I see the ToDos are finished.
