### ISSUE TITLE
Increase converage of regessions tests

### ISSUE THREAD

**Issue by katharinabr** [RWTH-EBC/AixLib#780]
In some packages the coverage by unit tests is low. Some example models don't have unit tests yet. 

The aim is to increase the converage of unit test by writing missing unit tests.

**Comment by AnaConstantin** [comment]
Check this branch as well, https://github.com/RWTH-EBC/AixLib/tree/issue718_EnhanceUnitTests, since it is were I already added some unit tests, back in May.
When generating unit tests, make sure you have the same software configuration as on the server running the CI (mainly Dymola Version), otherwise something that gives no warnings on one configuration might lead to warnings on another, and lead to a failed test.

**Comment by katharinabr** [comment]
Thanks, @AnaConstantin! I missed your issue. I'll close this issue because it's already part of #718 .
