### ISSUE TITLE
FastHVAC heat pump does not run in OpenModelica

### ISSUE THREAD

**Issue by broooooot** [RWTH-EBC/AixLib#864]
**Describe the bug**
In AixLib 0.9.1, whenever you use the FastHVAC.Components.HeatGenerators.HeatPump.HeatPump model the OpenModelica check fails with the message

> AixLib.DataBase.ThermalMachines.HeatPump.HeatPumpBaseDataDefinition: 4:3-4:82]: Failed to deduce dimension 1 of tableQdot_con due to missing binding equation"

**To Reproduce**
Just try to run the heat pump example within the FastHVAC package in OpenModelica.

**Additional context**
This does not appear to be a problem in Dymola 2020.

**Comment by jnettels** [comment]
I may have found a solution, it seems like the issue is caused by AixLib.DataBase.ThermalMachines.Chiller.ChillerBaseDataDefinition.
In an effort to reduce duplicate code, ChillerBaseDataDefinition currently simply extends HeatPumpBaseDataDefinition:

```
within AixLib.DataBase.ThermalMachines.Chiller;
record ChillerBaseDataDefinition "Basic chiller data"
    extends
    AixLib.DataBase.ThermalMachines.HeatPump.HeatPumpBaseDataDefinition(tableQdot_con = tableQdot_eva);
  parameter Real tableQdot_eva[:,:] "Cooling power table; T in degC; Q_flow in W";
```
This is where OMEdit's errors message comes from.
If we copy and adapt the contents of HeatPumpBaseDataDefinition like so:
```
within AixLib.DataBase.ThermalMachines.Chiller;
record ChillerBaseDataDefinition "Basic chiller data"

  extends Modelica.Icons.Record;
  parameter Real tableQdot_eva[:,:] "Cooling power table; T in degC; Q_flow in W";
  parameter Real tableP_ele[:,:] "Electrical power table; T in degC; Q_flow in W";
  parameter Modelica.SIunits.MassFlowRate mFlow_conNom
    "Nominal mass flow rate in condenser";
  parameter Modelica.SIunits.MassFlowRate mFlow_evaNom
    "Nominal mass flow rate in evaporator";
  parameter Real tableUppBou[:,2] "Points to define upper boundary for sink temperature";
  parameter Real tableLowBou[:,2] "Points to define lower boundary for sink temperature";
```
...the issue is resolved for my tests with the heatpump example. Not as elegant as before, but at least it is working. Should I provide a pull request with these changes?

**Comment by jnettels** [comment]
@DaJansenGit Could you (or someone else) be so kind to review the pull request? Right now I am not sure if this got any attention.

**Comment by DaJansenGit** [comment]
@jnettels Thanks for your participation in the FastHVAC library. In fact we don't want to copy the file to avoid redundancy in the library. Nevertheless we are interested in providing OpenModelica support as well. So I will see if there is another way to bypass the trial. I don't want to merge your pull request at the moment because of the reasons mentioned above. We will leave this issue open if anybody else wants to use our models with OpenModelica and needs a workaround.

**Comment by jnettels** [comment]
Thanks for the fast reply! I am aware that my workaround introduces redundancy and I hope there is a more elegant solution out there. Maybe some future update to openmodelica might fix the issue for us.

But seeing that this issue has been open for 5 month, I would like to encourage you to restore compatibility first and implement another solution once it actually works.

With that beeing said, I respect your decision and will not keep pressing further.
