### ISSUE TITLE
Considering ground temperature for equivalent air temperature calculation

### ISSUE THREAD

**Issue by PGorzalka** [RWTH-EBC/AixLib#922]
### Describe the bug
When looking for a way to include the influence of neighboured buildings to longwave irradiation in the ReducedOrder model, I found that currently all surfaces seem to be assumed horrizontal when it comes to the longwave radiation contribution to equivalent air temperature calculation by the classes in AixLib.ThermalZones.ReducedOrder.EquivalentAirTemperatures. They are influenced by longwave irradiation only from the sky instead of sky and ground depending on their tilt.

### To Reproduce
Look at equations calculating delTEqLW / delTEqLWWin in classes contained in AixLib.ThermalZones.ReducedOrder.EquivalentAirTemperatures.
PartialVDI6007: `delTEqLW=(TBlaSky - TDryBul)*hRad/(hRad + hConWallOut);`
VDI6007: `delTEqLWWin=delTEqLW;`
VDI6007WithWindow: `delTEqLWWin=(TBlaSky - TDryBul)*hRad/(hRad + hConWinOut);`

### Expected behavior
see additional context below

### Approach to solve issue
1. Add sky view factor according to Hensen and Lamberts in classes contained in AixLib.ThermalZones.ReducedOrder.EquivalentAirTemperatures, meaning `TBlaSky `is to be replaced by `phi*TBlaSky + (ones(n)-phi)*TGro ` where phi is a sky view factor
2. Introduce tilt angle as parameter for theses classes, making horizontal surfaces the default (which reproduces current behaviour) and calculate phi = (1 + cos(tilt)) / 2
3. Add tilt angle parameter where the classes are used

### Additional context
In the thesis of @mlauster (p. 63), [Hensen and Lamberts (2011): "Building performance simulation for design and operation"](http://www.academia.edu/download/32213664/Building_Performance_Simulation_for_Design_and_Operation.pdf) is cited when it comes to simplifications. However, equation (5.36) in that book includes ground temperature and a corresponding sky view factor, as does VDI 6007-1, eq. (33). Furthermore, according to [the model reference](https://www.ep.liu.se/ecp/096/013/ecp14096013.pdf) irradiation from the ground seems to be somehow included, but in a different way.

**Comment by DaJansenGit** [comment]
This seems to be a really high level question regarding how the VDI6007 was implemented into the model. @mlauster could you have a look on this?

**Comment by PGorzalka** [comment]
In the meantime, I have tried to solve this issue for myself. The main problem is that ground surface temperature is not available from the weather data that is used in AixLib. As a solution, I have programmed an interface to TRY data from DWD (instead of Energy+). These files include a column for terrestrial IR radiation. If you're interested, I'm happy to contribute this. However, afaik DWD TRY data is only available for Germany and thus won't solve the issue internationally.

**Comment by mlauster** [comment]
As already analyzed correctly, the current implementation considers only irradiation from the sky, not from the ground or other sources. The original VDI 6007 implementation considers irradiation from the ground, which can only be done by using TRY weather files, since epw-files do not contain the necessary input. Thus, when switching to epw.-files, I simplified our model. It allows neglecting the angle-dependency, which is non-linear and comparable complex. I did some sensitivity analysis and in typical TRY files, the difference between ground and sky irradiation is neglectable. So the typical error due to this simplification is small. 
Anyway, my works never focused on long-wave irradiation from further surfaces. This digs deep into urban topology modeling, since you would need to consider radiation exchange between multiple surfaces. E.g. the question is, which surface emits radiation and which absorps? This depends on their temperatures, which cannot be set as TBlaSky, since it depends on the surface's emissivity and heat transfer from the inside. To conclude, I think this is a complex topic, possibly already addressed by software like CitySim.
As a side note, "Horizontüberhöhung" due to buildings has already been modeled by Stanley Risch in `AixLib`, it might be worth combining all this when digging into radiation on urban scale.

**Comment by DaJansenGit** [comment]
@mlauster thanks for the detailed explanation. @PGorzalka I think for now this issue can be closed due to the small effects mentioned and the high effort and missing weather data except for germany. Please do not understand as cancellation, and if you don't agree and/or want to continue work/contribute please feel free to reopen the issue or contact me.

**Comment by PGorzalka** [comment]
As already mentioned here and discussed in [TEASER issue 727](https://github.com/RWTH-EBC/TEASER/issues/727), I adapted my custom TEASER multizone template to cover this, and therefore wrote an additonal DWD TRY Modelica reader that also provides ground thermal radiation. I _could_ contribute it to AixLib, if you find it helpful, but it would only make sense if there is an option in the VDI 6007 equivalent temperature calculation; and it would profit from an additional option `Input_HDirHor_HDifHor` in the `RadiationDataSource` enumeration of [IBPSA.BoundaryConditions.Types.mo](https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/BoundaryConditions/Types.mo) so you do not need to convert the radiation numbers in preprocessing.
